package com.example.evelyn;


import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;

import android.app.DatePickerDialog;
import android.app.ProgressDialog;
import android.content.ContentResolver;
import android.content.Intent;
import android.graphics.Bitmap;
import android.net.Uri;
import android.os.Bundle;

import android.provider.MediaStore;
import android.text.TextUtils;
import android.view.View;
import android.webkit.MimeTypeMap;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.Button;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.Toast;

import com.google.android.gms.tasks.OnFailureListener;
import com.google.android.gms.tasks.OnSuccessListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.storage.FirebaseStorage;
import com.google.firebase.storage.StorageReference;
import com.google.firebase.storage.UploadTask;

import java.util.Calendar;
import java.util.HashMap;

import de.hdodenhof.circleimageview.CircleImageView;



public class SettingsActivity extends AppCompatActivity {
    private CircleImageView circleImageView;
    private EditText donationdate,fullnameEditText,ageEditText,thanaEdit,contactEdit;
    private Uri imageUri;
    private Bitmap imageStore;
    private ImageView calenderIcon;
    private AutoCompleteTextView districtEdit,hospitalEdit,bloodGroupEditText;

    private FirebaseAuth mAuth;
    private FirebaseUser currentUser;
    private DatabaseReference RootRef;
    private StorageReference storageReference;
    private ProgressDialog loadingBar;

    String currentUserID;
    DatePickerDialog.OnDateSetListener setListener;


    public String[] districts = { "Ahmadnagar", "Akola", "Amravati", "Aurangabad", "Bhandara", "Bid", "Buldana",
            "Chandrapur", "Dhule",
            "Gadchiroli", "Gondiya", "Hingoli", "Jalgaon", "Jalna", "Kolhapur", "Latur", "Mumbai", "Mumbai(Suburban)",
            "Nagpur", "Nanded",
            "Nandurbar", "Nashik", "Osmanabad", "Parbhani", "Pune", "Raigarh", "Ratnagiri", "Sangli", "Satara",
            "Sindhudurg", "Solapur",
            "Thane", "Wardha", "Washim", "Yavatmal", "Ahmadabad", "Amreli", "Anand", "Banas Kantha", "Bharuch",
            "Bhavnagar", "Dohad", "Gandhinagar", "Jamnagar",
            "Junagadh", "Kachchh", "Kheda", "Mahesana", "Narmada", "Navsari", "Panch Mahals", "Patan", "Porbandar",
            "Rajkot", "Sabar Kantha", "Surat", "Surendranagar", "Tapi",
            "The Dangs", "Vadodara", "Valsad", "Ambala", "Bhiwani", "Faridabad", "Fatehabad", "Gurgaon", "Hisar",
            "Jhajjar", "Jind", "Kaithal", "Karnal", "Kurukshetra", "Mahendragarh",
            "Mewat", "Palwal", "Panchkula", "Panipat", "Rewari", "Rohtak", "Sirsa", "Sonipat", "Yamunanagar" };

    String[] hospitals = {
            " Anand Rishiji Hospital & Medical Research Centre", "Bagal Nursing Home", "City Care Hospital",
            "Daule Hospital",
            "Deepak Hospital",
            "Deshpande Hospital",
            "Dr Anbhule Hospital",
            "Dr Bade Hospital Surgical & Maternity Home",
            " Dr Bakul Palwe Accidentand Surgical Hospital",
            " Dr Gore Eye Hospital",
            " Dr Kalamkar Hospital",
            " Dr Khalkar Hospital",
            "Dr Sunil Jadhav Hospital",
            " Dr V N Deshpande Accident & Superspeciality Centre",
            " Gajanan Hospital & Advanced Endoscopic Ent Surgery",
            "Galaxy Hospital",
            " Jeevandhara Hospital",
            "Kapase Eye Clinic",
            "Khandelwal Children Hospital",
            " Kulkarni Ent & Maternity Hospital",
            "Naik Paediatric Surgery Center",
            "  Navoday Surgical & Burn Clinic",
            " Nisar Hospital & Materiyt Home",
            " Noble Hospital And Research Centre",
            "Pandit Accident Hospital",
            "Pranav Hospital Multispecialty And Icu Center",
            " Sarthak Hospital",
            "Sarvodaya Hospital(dr Sonambekar Hospital)",
            "Satalkar Hospital",
            "Shree Sai Sahyadri Multispecialty Hospital",
            "Siddhivinayak Childrens Hospital & Critical Care Centre",
            "Sunder Netralaya",
            "  Swasthya Hospital Medical Research Center",
            "Tarde Hospital",
            "Thorat Superspeciality Eye Care",
            "Wagh Nursing Home",
            "Zarekar Hospital",
            "Zende Hospital",
            " Bule Hospital",
            "Lokmanya Hospital",
            "Abhijit Clinic And Dr Achari Hospital",
            "Dr Boob Hospital",
            "Kothari Hospital",
            "Phadke Hospital",
            "Sai Poly Clinic & Endoscopy Centre",
            "Wagh Hospital",
            "Mauli Multispeciality Hospital",
            "Onkar Hospital & Multispeciality",
            "Dr Maid Hospital & Maternity Home",
            "Chaitanya Hospital",
            "Dr Satpute Hospital",
            "Kute Hospital & Laparoscopy Centre",
            "Pophale Hospital Pvt. Ltd.",
            "Rasal Hospital",
            "Sai Suman Hrudayalaya & Critical Care",
            "Tambe Hospital",
            "Vamanrao Itape Homoepathic Medical College & Hospital",
            "Sai Multispeciality Hospital",
            "Shree Hospital",
            "Akola Accident Clinic",
            "Akola Eye Hospital",
            "Harish Hospital",
            "Heda Hospital",
            "Murarka Hospital",
            "Om Multispeciality Hospital",
            "Shree Samarth Hospital",
            "Siddhivinayak Hospital",
            "Vitthal Hospital",
            "Deshmukh Eye Hospital",
            "Dr Vijay agrawal eye Clinic",
            "Galaxy Hospital & Apex Critical Care",
            "Get Life Health Care Pvt Ltd",
            "Hi Tech Critical Care And Bonde Hospital",
            "Mahaveer Hospital",
            "Navjivan Hospital",
            "Netra Jyot Eye Hospital",
            "Parashri Speciality Hospital",
            "  Patil Ent & Cancer Hospital",
            "Vyawahare Netralaya",
            "Yash Netralaya & Bal Ruganalay",
            "Bardia Hospital",
            "Apex Super Speciality Hospital",
            "Asian Citicare Superspeciality Hospital",
            "Aurangabad Institute Of Medical Sciences Pvt Ltd",
            " Brain Hospital",
            "Century Multispeciality Hospital",
            " Chhabda Hospital",
            "Ciigma Hospital",
            "Dande Diabetes & Heart Care Centre",
            "Daulat Memorial Hospital",
            "Devdatt Palnitkar Hospital",
            " Dongaonkar Superspeciality Eye Hospital",
            " Dr Hedgewar Rugnalaya",
            "  Drusti Eye Institute Pvt Ltd",
            "Dunakhe Hospital",
            "Gade Hospital",
            "Hazari Nursing Home",
            "Hitech Critical Care Instutute",
            "Hyaat Multispeciality Hospital Pvt Ltd",
            "Jhunjhunwala Hospital",
            " Kabra Hospital",
            "Kamalnayan Bajaj Hospital (mmri)",
            " Kodlikeri Hospital & Trust",
            "Manik Hospital & Research Centre",
            "   Mit Hospital & Research Institute",
            "Niramay Super Speciality Balrugnalaya Pvt Ltd",
            "Padmavati Hospital",
            "Patwardhan Hospital",
            "Prestige Hospital",
            "Ruby Heart Care Centre Pvt Ltd",
            " Sachin Hospital",
            "Sai Urology Hospital",
            "Sanjeevani Childrens Hospital",
            " Saoji Pratishthan & Research Centre",
            " Seth Nandlal Dhoot Hospital",
            "Sumananjali Nursing Home",
            " Sushila Netralay",
            " Suyash Nursing Home",
            " Tirupati Hospital Icu & Trauma Centre",
            " Tirupati Netralaya & Dental Hospital",
            "United Ciigma Hospital",
            " Vasan Eye Care Hospital",
            " Wadgaonkar Eye Hospital",
            "Lodha Hospital",
            "  Phoenix Critical Care Centre",
            " Vithai Hospital & Research Centre",
            "Jadhav Hospital & Maternity Home",
            "Shivam Netralaya & Nursing Home",
            " Indrakshi Eye Care",
            " Laksh Hospital  Vyas Fracture Accident & Ayurveda Hospital",
            "Nakade Nursing Home",
            " Dr Chinchole Netra Ruganalay & Laser Centre",
            " Laddhad Hospital",
            "Mehetre Hospital",
            " Mehkar Multispeciality Hospital",
            "C H L Multispeciality Hospital & Research Centre",
            "Manwatkar Multispeciality Hospital",
            "Sainani Nursing Home",
            " Sanjeevani Hospital",
            "Shri Sai Divine Cure Multispeciality Hospital",
            " Spandan Heart Hospital",
            "  Wasade Hospital",
            " B K L Walawalkar Hospital Diagnostic & Research Centre",
            " Chiranjeev Balrugnalay",
            " Desai Hospital",
            " Life Care Hospital",
            " Patankar Nursing Home",
            "Aastha Intensive Care Centre",
            " Chaitanya Hospital",
            "Institute Of Urology",
            "Niramaya Hospital",
            "Om Critical Care Centre",
            "Seva Superspeciality Critical Care Centre",
            "Shri Siddheshwar Multispeciality Hospital",
            " Sitaram Hospital",
            "B J Hospital & Research Institute",
            " Central Hospital & Critical Care Centre",
            "Gondia Care Hospital",
            " Konark Superspeciality Hospital Pvt Ltd",
            " New Life Hospital",
            " Saipushpa Accident Hospital",
            "Vishvanath Hospital",
            "Arogya Deep Hospital",
            "Ashwini Multispeciality Hospital",
            " Chinmay Hospital & Critical Care Centre",
            " Disha Eye Hospital",
            "Gajre Hospital",
            "Indo American Cardiovascular Center",
            " Indu Hospital",
            " Khadke Accident Hospital",
            " Lokmanya Hospital Criticalcare & Multispeciality Centre",
            " Madhur Urology & Stone Speciality Clinic & Maternity Home",
            " Mahajan Hospital",
            "Mulik Netra Chikitsalaya",
            " Netram Hospital",
            " Nimjai Healthcare Pvt Ltd",
            "Orchid Multispeciality Hospital",
            " Sahyog Critical Care Centre",
            " Shree Gajanan Heart & Eye Hospitals Pvt. Ltd",
            " Shri Saijeevan Hospital",
            " Shri Surgical & Maternity Home",
            " Siddhesh Hospital",
            "Siddhivinayak Hospital",
            " Suyash Hospital",
            " Vijayendra Hospital & Maternity Home",
            " Vinod Hospital",
            " Vivekanand Netralaya & Phaco Centre",
            "Kolte Hospital",
            " Deepak Hospital",
            " Guru Ganesh Mutha Hospital Pvt Ltd",
            " Jalna Medical Foundation & Research Centre Pvt Ltd (vivekanad Hospital)",
            " Karwa Hospital",
            "Runwal Accident Clinic",
            " Niramay Hospital",
            "Shri Sai Surgical & Maternity Hospital",
            "  Apple Hospital",
            "Aster Aadhar Hospital",
            " City Hospital",
            " Drishti Deep Netra Seva (pacho & Eye Care Centre)",
            "Galaxy Hospitals Ltd",
            " Ishan Hospital",
            " Janaki Nursing Home",
            " Kolhapur Cancer Centre",
            "  Kolhapur Institute Of Orthopaedics & Trauma",
            "Kudalkar Hospital",
            "Lokmanya Hospital Pvt. Ltd",
            "Lotus Hospital And Research Centre",
            " Mahant Hospital",
            "Modak Hospital Orthopedic & Fracture Care",
            " Mudhale Nursing Home",
            "Nirmal Nursing Home",
            "Patil Institute Of Orthopaedic Sciences  Multispeciality  Hospitaljaysingpure",
            " Pragati Netra Rugnalaya",
            "Ramkrishna Hospital",
            " Rangnath Hospital",
            "Rbj Hospital Private Limited",
            " Shri Sai Hospital",
            " Shri Siddhivinayak Heart Hospital",
            "Siddhagiri Hospital & Research Centre",
            " Siddhivinayak Nursing Home",
            " Swastik Hospital",
            "  Vardhan Hospital For Children",
            "Vasan Eye Care Hospital",
            " Western India Institute Of Neurosciences",
            " Alpha Superspeciality Hospital",
            " Dr S B Gugale Memorial Hospital",
            "Jatal Hospital",
            " Latur Cancer & Laparoscopy Centre",
            "Mamta Hospital",
            " Planet Critical Care Centre Pvt Ltd",
            "   Prabhawati Multispecialty Hosapital & Research Centre",
            "Sadasukh Hospital",
            " Sahara Hospital",
            "Shri Venkatesh Hospital",
            "Vivekanand Hospital",
            "Lifecare Hospital & Research Centre",
            "Aashirwad Maternity &general Nursing Home",
            "Aastha Hospital",
            "Abhishek Nursing Home",
            "Adittya Eye Clinic",
            "Aditya Jyot Eye Hospital Pvt Ltd",
            "Advance Eye Hospital & Institute",
            "Aggarwal Eye Hospital",
            "Agrawal Eye Hospital",
            "Akanksha Materntiy & Surgical Hospital",
            "Akshar Eye Clinic",
            " Amardeep Nursing Home",
            "  Ameya Orthopaedica Centre",
            " Amruta Surgical & Maternity Home",
            "Anand Nursing Home",
            "Apex Hospitals",
            " Apex Hospitals Mulund",
            " Apex Kidney Care",
            "Apex Kidney Care",
            "  Apex Kidney Care",
            "Apex Kidney Care",
            "Apollo Spectra Hospitals A Unit Of Apollo Specialty Hospitals Pvt Ltd",
            "  Apollo Spectra Hospitals A Unit Of Apollo Specialty Hospitals Pvt Ltd",
            "Arihant Eye Care Hospital",
            "Arihant Heart Clinic",
            "Asha Poly Clinic & Sheetal Nursing Home",
            " Ashirwad Child & Surgical Hospital",
            " Ashirwad Heart Hospital",
            " Ashirwad Hospital & Polyclinic",
            " Ashirwad Maternity & Nursing Home",
            "Ashirwad Maternity & Nursing Home",
            "Ashirwad Nursing Home",
            "Ashwini Hospital & Iccu",
            "Asian Eye Institute & Laser Centre",
            "Asian Eye Institute & Laser Centre",
            "Asian Heart Institute",
            "Asian Institute Of Oncology Pvt Ltd",
            "Atul Lok Hospital",
            "Balaji Heart Hospital And Diagnostic Centre Pvt Ltd",
            "Bathia Hospital & Eye Clinic",
            "Bcj Hospital  Asha Parekh Research Centre",
            "Bhargava Nursing Home",
            "Bhartiya Arogya Nidhi Shet Kantilal C Parikh General Hospital",
            "Bhatia Hospital",
            "Bhojraj Chanrai Sankara Eye Hospital",
            "Bombay Hospital & Medical Research Centre",
            "Breach Candy Hospital Trust",
            "Bses Mg Hospital",
            "City Hospital & Recearch Centre",
            "Criticare Hospital & Research Centre",
            "Crystal Hospital Ltd",
            "Cumballa Hills Hospital And Heart Institute",
            "Dattatreya Nursing Home",
            "Dewang Nursing Home Pvt Ltd",
            "Dhanvantari Hospital",
            "Dhanwantary Hospital & Iccu",
            "Diamond Hospital",
            "Dna Multispeciality Hospital",
            "Doctor Eye Institute Pvt Ltd",
            "Doshi Maternity & Nursing Home",
            "Doshi Nursing Home & Icu",
            "Dr Balabhai Nanavati Hospital",
            "Dr Baliga Nursing Home",
            "Dr Bhatias Ruby Hospital",
            "Dr Bothras Hospital",
            " Dr Dipak Desais Ent Hospital",
            " Dr Gala Nursing Home",
            " Dr Hiren Mehta Eye Care Center",
            "Dr Kamdars Nursing Home",
            "Dr Kulkarni Hospital",
            "Dr L H Hiranandani Hospital",
            "Dr Malwankars Romeen Nursing Home",
            "Dr Mukhis Raj Hospital",
            "Dr Patani Eye Clinic",
            "Dr Pattnaik Hospital",
            "Dr Rane Hospital (p) Ltd",
            "Dr Sabnis Maternity & Nursing Home",
            "Dr Savla Polyclinics & Nursing Home",
            "Dr Shetty Ent Hosptial",
            "Dr Shetty Nursing Home",
            "Dr Simandhar Eye Care Centre",
            "Dr Sonagra Medical & Surgical Centre",
            "Dr Vaze Hospital",
            "Dr Vora Premature Critical Care & General Hospital",
            "Dr Zikrullah Khan Habib Hospital Pvt Ltd",
            "E N T Clinic and Deafness Centre",
            "Ear Nose & Throat Hospital",
            "Excel Urology Centre",
            "Eye Essential Hospital",
            "Fauziya Hospital",
            "Fortis Hospitals Ltd Mulund",
            "Furia Eye Clinic",
            "Gandhi Nursing Home",
            "Gautam Hospital",
            "Global 5 Health Care",
            "Global Hospital Super Speciality & Transplant Centre ( A Unit Of Centre For Digestive & Kidny Diseases (india) Pvt Ltd)",
            "Godrej Memorial Hospital",
            "Gokul Nursing Home & Iccu",
            "Gomathi Eye Centre",
            "Guru Nanak Hospital",
            "H J Doshi Ghatkopar Hindu Sabha Hospital",
            "Hinduja Healthcare Limited",
            "Hira Mongi Navneet Hospital",
            "Holy Family Hospital",
            "Holy Spirit Hospital",
            "Holy Trinity Hospital",
            "Inlaks General Hospital",
            "Ishita Nursing Home",
            "Jain Eye Clinic",
            "Jaslok Hospital And Research Centre",
            "Jay Polyclinic Maternity & Nursing Home",
            "Jeevan Jyot Hospital",
            "Jewel Hospital",
            " Joy Hospital Pvt Ltd",
            " K L S Memorial Hospital",
            " Kapadia Multispeciality Hospital",
            "Kataria Eye Clinic",
            "Kedar Nursing Home",
            "Kedia Nursing Home",
            "Khandwalas Eye Hospital & Hem Polyclinic",
            "Khushal Hospital & Maternity Home",
            "Kini Nursing Home",
            "Kirit Nursing Home",
            "Kohinoor Hospitals Private Limited",
            "Kokilaben Dhirubhai Ambani Hospital",
            "Kolekar Nursing Home",
            "Krishna Cardiac Care Centre",
            " Krishna Eye Care Centre",
            "Krishna Eye Centre",
            "Krishna Nursing Home",
            "Lakshmi Nursing Home",
            "Laparoscopy & Scopy Centre",
            "Laxmi Health Care Centre & Iccu",
            "Lilavati Hospital & Research Centre",
            "Lux Hospital",
            "Maa Nursing Home And Netrajyoti Eyecare Centre",
            "Madhu Polyclinic & Nursing Home",
            "Mahatme Health & Hapiness Hospital",
            "Mahek Nursing Home",
            "Mallika Hospital",
            "Malpani Eye Hospital & Laser Centre",
            "Mamta Maternity & Nursing Home",
            "Mangala Hospital",
            "Masrani Hospital For Woman & Mimas",
            "Matushree Maternity Surgical & General Nursing Home",
            "Medicare Hospital",
            "Megha Surgical Hospital",
            "Meher Ambe Hospital",
            "Modi General Hospital & Icu",
            "Mukund Maternity & Surgical Nursing Home",
            "Mulund Nursing Home",
            "Namita Polyclinic And Hospital",
            "National Hospital & ICCU",
            "Navnirman Maternity & Surgical Hospital",
            "Nefrons Mission Nephro Care Pvt Ltd",
            "Netrajyoti Eye Care Centre",
            "Neway Hospital",
            "Nirmal Nursing Home",
            "Noble Hospital",
            "Nulife Hospital Pvt Ltd",
            "Nupur Nursing Home",
            "Om Navjeevan Hospital Pvt Ltd",
            "Omkar Hospital",
            "Omkar Hospital",
            "Orbit Eye Hospital",
            "Ortho - Max Hospital",
            "Padmashree Nursing Home",
            "Paramount General Hospital & Iccu",
            "Paras Nursing Home",
            "Parekh Eye & Child Clinic",
            " Parvish Nursing Home Pvt Ltd",
            " Patel Nursing Home",
            " Phoenix Hospitals Pvt Ltd",
            " Pikale Hospital",
            " Platinum Hospital",
            " Pooja Nursing Home Pvt Ltd",
            " Prince Aly Khan Hospital",
            " Punamiya Hospital",
            " Purohit Hospital (Dir Mailer)",
            "R G Stone Urological Research Institute",
            "R G Stone Urology & Laparoscopy ( Andheri (w)c",
            "R G Stone Urology Centre (hira Mongi Navneet Hospital Mulund)",
            "R J Ganatra Nursing Home",
            "Ravi Surgical Nursing Home",
            "Riddhi eye clinic",
            "Riddhi Siddhi Hospital Pvt Ltd",
            "Riddhi Vinayak Critical Care And Cardiac Centre",
            "Rohit Nursing Home",
            "S L Raheja Hospital",
            "Saarthi Health Care",
            "Saarthi Hospital",
            "Sahu Eye Hospital (a Branch Of Kamal Netralaya Pvt Ltd)",
            "Sai Aashirwad Hospital",
            "Sai Hospital",
            "Sai Hospital",
            "Sai Hospital",
            "Sai Kripa Hospital",
            "Sai Swayam Maternity & Nursing Home",
            "Saifee Hospital",
            "Sanchaiti Hospital Private Limited",
            "Sanghvi Eye & Diabetes Care Centre",
            "Sanjay Eye Clinic",
            "Sanjeevani Surgical & General Hospital",
            "Sanjivani Hospital",
            "Sapna Health Care Centre Pvt Ltd",
            "Sas Healthcare (p) Ltd",
            "Satyam Multi Speciality Hospital & Trauma Centre",
            "Satyam Nursing Home",
            "Seven Eleven Hospital",
            "Sevenhills Healthcare Private Limited",
            "Shah Children Hospital & New Born Care Centre",
            "Shah Eye Clinic & Nurshing Home",
            "Shetty Endoscopic Surgical Centre",
            "Shivam Hospital",
            "Shivam Netram Eye Hospital",
            "Shraddha Hospital",
            "Shraddha Polyclinic & Nursing Home",
            "Shree Balaji Hospital",
            "Shree Eye Care",
            "Shree Krishana Maternity & Child Care",
            "Shree Krishna Hospital",
            "Shree Nursing Home",
            "Shree Ram Eye Care Centre",
            "Shree Ramnath Eye Care",
            "Shree Sai Clinic",
            "Shree Sai Hospital",
            "Shree Sukhshanti Hospital",
            "Shreepal Netralaya",
            "Shri Bal Chikitsalaya",
            "Siddhi Nursing Home",
            "Smt S R Mehta & Sir K P Cardiac Institute",
            "Snehal Ent Clinic",
            "Sona Medical Centre",
            "Speciality Ear Nose Throat Hospital",
            "Srushti Orthotech Hospital",
            "St Elizabeths Hospital",
            "Sujay Hospital",
            "Sulochan Eye Hospital",
            "Suman Eye Clinic & Surgery Centre",
            "Sumangal Hospital",
            "Surana Hospital & Research Centre",
            "Surana Sethia Hospital & Research Centre",
            "Surya Childrens Hospital",
            "Sushrut Hospital & Research Centre",
            "Sushrut Maternity And Surgical Nursing Home",
            "Swastik Nursing Home",
            "Swastika Nursing Home",
            "The Eye Super Specialties",
            "Trivedi Maternity & Nursing Home",
            "Upadhyaya Nursing Home",
            "V Care Hospital & Icu",
            "Vardhaman Hospital & Iccu",
            "Vardhman Iccu & Nursing Home",
            "Vasan Eye Care Hospital",
            "Ve-care Hospital",
            "Vibha Care Home The Family Hospital",
            "Vijayalaxmi Maternity, Surgical & General Hospital",
            "Wockhardt Hospitals Ltd",
            "Zenith Hospital",
            "Zynova Heart Care Pvt Ltd",
            "Adishakti Hospital",
            "Akshar Eye Institute + Laser Dental Clinic",
            "Ambade Eye Hospital",
            "Anantwar Eye Hospital",
            "Aniket Nursing Home",
            "Apulki Vairagade Hospital",
            "Arneja Heart Institute",
            "Arogyam Superspeciality Hospital",
            "Asha Hospital",
            "Ashwini Kidney & Dialysis Centre",
            "Avanti Institute Of Cardiology Pvt Ltd",
            "Baraskar Multispeciality Hospital & Dialysis Centre",
            "Brain, Spine Accident & Head Injury Care Hospital",
            "Care Hospital",
            "Center Point Hospital",
            "Central Avenue Critical Care Hospital & Iccu",
            "Central India Institute Of Hemotology & Oncology",
            "Central Indias Child Hospital",
            "Chandak Nursing Home",
            "City Hospital",
            "Crescent Nursing Home And Iccu",
            "Cure It Hospital Pvt Ltd",
            "Dashputra Hospital & Eye Care",
            "Dr Dande Hospital",
            "Dr Gaikwad Critical Care Centre Pvt Ltd",
            "East End Hospital & Critical Care Unit",
            "Evista Eye Care Centre",
            "G B Multispeciality Hospital Pvt Ltd",
            "Gandhi Maternity & Nursing Home",
            "Gillurkar Multispeciality Hospital",
            "Green City Hospital & Nursing Home",
            "Gupta ENT Hospital",
            "Hardas Eye Hospital",
            "Hi Tech Hospital",
            "Hope Hospital",
            "Jaiswal Children Hospital",
            "Janata Maternity Home & Hospital",
            "Jasleen Eye Hospital",
            "Kalptaru Maternity & Surgical Nursing Home",
            "Keshav Hospital",
            "Ketki Nursing Home & Urology Hospital",
            "Khalatkar Hospital",
            "Krims Hospital [ketki Research Institute Of Medical Sciences Ltd]",
            "Kriplani Hospital",
            "  Kunal Hospital Critical Care & Trauma Centre",
            "  Lata Mangeshkar Hospital",
            "Life Line Hospital",
            "Lotus Hospital & Research Centre",
            "Mahajan Ortho & Surgical Hospital",
            "Mahatme Hospital Pvt Ltd",
            "Maxcare Hospital & Laparoscopy Institute",
            "Maya Hospital & Research Centre",
            "Meditrina Institute Of Medical Sciences",
            "Metro City Hospital & Critical Care Centre",
            "Midas Multispeciality Hospital Pvt Ltd",
            "Nagpur Neuro Sciences Clinics Pvt Ltd",
            " Neeti Clinic Pvt Ltd",
            " Nerkar Hospital",
            "Niramay Hospital",
            "Niyakshi Hospital",
            "Oke Eye Hospital",
            "Om Women Hospital",
            "Orange City Hospital & Research Institute",
            "Ortho Relief Hospital & Research Centre",
            "Platina Heart Hospital (a Unit Of Platina Hospital Pvt Ltd)",
            "Prasad Hospital",
            "Prestige Nursing Home",
            "Radiance Hospital Pvt Ltd",
            "Rahate Surgical Hospital",
            "Rathi Nursing Home",
            "Sanjeevani Hospital",
            "Sawali Orthopaedic Hospital",
            "Shanti Prabha Nursing Home",
            "Shat-ayu Hospital & Research Centre",
            "Shraman Multispeciality Hospital& Critical Care",
            "Shravan Hospital & Kidney Institute",
            "Shree Hospital & Critical Care",
            "Shree Krishna Hrudayalaya & Critical Care Centre",
            "Shreeji Hospital",
            "Shri Sai Netralaya",
            "Shrikhande Hospital & Research Centre Pvt Ltd",
            "Sood Eye Hospital For Advance Eye Care Pvt Ltd",
            "Spandan Heart Inst & Research Centre",
            "Sreeprabha Orthopaedic & Accident Hospital",
            "Suraj Eye Institute",
            "Suretech Hospital & Research Centre Ltd",
            "Sushrut Hospital & Research Centre",
            "Swami Vivekanad Medical Mission",
            "Upcharya An Institute Of Orthopaedic Surgery & Trauma Care Centre",
            "Vasan Eye Care Hospital",
            "Wockhardt Heart Hospital",
            "Wockhardt Hospitals",
            "Kimaya Jaiswal Hospital",
            "Shantaram Ortho & Surgical Hospital",
            "Lavekar Hospital",
            "Nanded Accident & Orthopaedic Hospital",
            "Shrinath Maternity & Child Hospital",
            "Toshniwal Chest Hospital Maternity & Nursing Home",
            "Anant Hospital",
            "Children & General Hospital",
            "Aashadatta Maternity Hospital",
            "Sushrut Nursing Home",
            "Deore Hospital",
            "Om Netralaya & Dental Clinic",
            "M J Hospital & Critical Care Centre",
            "Prayas Superspeciality Hospital Pvt Ltd",
            "Ashwini Hospital",
            "Pushpak Hospital",
            "Siddharth Hospital",
            "Aayush Hospital",
            "Ankur Maternity Home & Diagnostc Centre",
            "Apollo Hospital",
            "Arihant Hospital",
            "Ashwini Accident Multispeciality Hospital",
            "Bhagwati Superspeciality Endoscopy Hospitals Llp",
            "Birla Superspeciality Eye Hospital",
            " Chintamani Hospital",
            " Chirayu Childrens & Eye Hospital",
            " Curie Manavata Cancer Centre",
            "Deogaonkar Hospital",
            "Divyajyot Hospital",
            "Dr Aware Hospital",
            "Dr Bagul Hospital",
            "Dr Bapaye Hospital",
            "Dr Pimparikar Hospital",
            "Dr Suryawanshi Eye Hospital",
            "Healing Touch Angiography & Cardiac Surgery Centre Pvt Ltd",
            "Jantara Hospital",
            "Kalpataru Multispeciality Hospital",
            "Krishna Hospital & Critical Care Centre",
            "Kshitij Endoscopy Centre",
            "Kute Eye Hospital",
            "Life Care Hospital",
            "Maharshi Heart & Critical Care Hospital",
            "Maher Hospital",
            "Mercury Superspeciality Hospital",
            "Mvpa Vasantrao Pawar Medical College",
            "Navsanjeevani Hospital",
            "Nelson Memorial Children Hospital",
            "Om Hospital",
            "Prasanna Balrugnalay",
            "Rajebahadur Hospital & Research Centre Pvt Ltd",
            "Ramalayam Hospital",
            "Ramole Eye Hospital & Dental Clinic",
            "Sadguru Hospital",
            "Sai Hospital",
            "Sai Shree Superspeciality Hospital",
            "Sai Siddhi Hospital",
            "Sanjeevani Hospital",
            "Sant Krupa Multispeciality & Accident Hospital",
            "Sarthak Hospital",
            "Shah Hospital",
            "Shatabdi Super Speciality Hospital",
            "Shivam Eye Hospital",
            "Shree Balaji Super Speciality Hospital",
            "Shree Saibaba Heart Institute & Research Centre",
            "Shreeya Hospital",
            "Shreeyash Hospital",
            "Shri Guruji Rugnalaya",
            "Six Sigma Medicare & Research Ltd",
            "Sonawane Heart Care Hospital And Research Centre",
            "Sonawane Hospital Yeola",
            "Sujata Birla Hospital & Medical Research Center",
            "Sukhakarta Hospital & Maternity Hospital",
            "Sukhatme Maternity Home",
            "Sunrise Hospital Criticare Hospital & Research Centre",
            "Surya Multispeciality Hospitals Pvt Ltd",
            "Susheel Eye Institute",
            "Suvichar Hospital",
            "Suyog Hospital",
            "Synergy Hospital & Research Centre",
            "Torne Ent Hospital & Research Centre",
            "Trimurti Multispecialty Hospital",
            "Tulsi Eye Hospitals",
            "Vakratunda Hospital Pvt Ltd",
            "Vasan Eye Care Hospital",
            "Vijan Cardiac & Critical Care Centre",
            "Vimal Ent Hospital",
            "Vishwesh Childrens Hospital",
            "Wockhardt Hospitals Ltd",
            "Janseva Hospital",
            "Parijat Hospital",
            "Shivai Hospital",
            "Siddhivinayak Super Speciality Hospital",
            "Yashwant Multispeciality Hospital",
            "Aayush Multi Speciality Hospital & Diognostic Centre",
            "Acharya Shri Nanesh Hospital",
            "Avadhoot Hospital & Iccu",
            "Dake Hospital",
            " Divine Multispeciality Hospital",
            " Dr A Tungekars Hospital",
            " Dr D Y Patil Hospital & Research Centre",
            "Dr Dokes Shraddha Hospital",
            "Dr G D Pol Foundations Ymt General Hospital",
            "Dr Jairajs Hospital",
            "Dr Mahajan Hospital & Itc",
            "Dr R N Patil Suraj Hospital",
            "Dr Singh City Hospital & Medical Research Centre Pvt Ltd",
            "Dr Sonawanes Hospital",
            "Dr Yewale Multispeciality Hospital For Children",
            "Dr. Ajayan Multispeciality Hospital",
            "Fortis Hiranandani Hospital",
            "Gade Hospital",
            "Gandhi Hospital",
            "Heritage Hospital",
            "Lotus Multispeciality Hospital & Icu",
            "Mangal Prabhu Nursing Home",
            "Mangaldeep Hospital",
            "Mgm Hospital & Research Centre",
            "Mgm New Bombay Hospital",
            "Mitr Health Care Hospital",
            "Mody Hospital & Icu",
            "Navjeevan Hospital & Iccu",
            "Navjivan Hospital",
            "Niramaya Holistic Health Services Pvt Ltd",
            "Noble Care Hospital",
            "Ojas Nursing Home",
            "Om Gagangiri Hospital",
            "Patoria Eye Clinic",
            "Sai Seva Hospital & Iccu",
            "Sanjivani Hospital",
            "Shivam Eye Foundation",
            "Shree Eye Hospital",
            "Shree Hospital",
            "Shushrusha Heart Care Centre & Speciality Hospital",
            "Sterling Wockhardt Hospital",
            "Sunrise Multispeciality Hospital",
            "Suruchi Eye Centre",
            "Suyash Hospital",
            " Suyash Nursing Home",
            " Suyash Surgical & Maternity Home",
            "Terna Sahyadri Speciality Hospital & Research Center",
            "Uran Children Hospital & Premature Care",
            "Vasan Eye Care Hospital",
            "Niramay Hospital",
            "Shendge Hospital Research Centre",
            "Suvidha Hospital & Icu Centre",
            "Malaba Hospital",
            "Deshmukh Hospital",
            "Ganesh Netralaya",
            "Swati Criticare Icu & Accident Hospital",
            "Bhagyajaya Hospital",
            "Bhandare Hospital",
            "Giriraj Hospital",
            "Niramaya Medical Foundation & Research Center (P) Ltd",
            "Shree Hospital",
            "Lonkar Hospital & Intensive Care Unit",
            "Sonone Surgical & Ophthalmic Hospital",
            "Kamshet Hospital",
            "Ashirwad Hospital",
            "Kamat Hospital",
            "Parmar Hospital",
            "Yash Hospital",
            "Pravara Rural Hospital & Medical College",
            "Gade Hospital",
            "Gujarathi Hospital",
            "Sai Hospital",
            "Sanjeevan Hospital",
            "Shinde Nursing & Multispeciality Hospital",
            "Siddhakala Hospital",
            "Matoshri Hospital",
            "Shraddha Hospital",
            "Aadhar Hospital",
            "Abane Hospital",
            "Ace Hospital",
            "Aditya Eye Clinic",
            "Agarwal Maternity And General Hospital",
            "Aims Hospital & Research Centre",
            "Ambekar Hospital",
            "Ameya Netralaya",
            "Amrut Hospital",
            "Amrut Hospital & Research Centre",
            "Anand Hospital",
            "Ankur Hospital & Diagostic",
            "Apollo Spectra Hospital ( Unit Of Apollo Specilty Hospitals Pvt Ltd",
            "Argade Hospital & Maternity Home",
            "Bade Accident And Multispeciality Hospital",
            "Bhagawati Netralaya",
            "Bhalerao Ent Hospital",
            "Bhandari Maternity & Nursing Home",
            "Bharati Hospital & Research Centre",
            "Chaitanya Hospital",
            "Chaitanya Hospital & Nursing Home",
            "Chavan Hospital",
            "Cimets Inamdar Multispeciality Hospital",
            "Columbia Asia Hospital",
            "Core Hospital",
            "Deenanath Mangeshkar Hospital & Research Centre",
            "Deendayal Memorial Hospital",
            "Deep Eye Hospital",
            "Deodhar Eye Hospital",
            "Deoyani Multispeciality Hospital",
            "Devadhar Nursing Home",
            "Divya Eye Clinic",
            "Diwan Hospital",
            "Dr Gaikwad Diabetes Centre",
            "Dr Makan Surgical Maternity & Accident Hospital",
            "Dr Raskar Eye Hospital",
            "Dr. Ghatkar Hospital",
            "Gadkari Eye Centre",
            "Gandhi Accident & General Hospital",
            " Gandhi Nursing Home",
            " Global Hospital",
            "Gokhale Hospital",
            "Hardikar Hospital",
            "Harsh Hospital",
            "Imax Multispeciality Hospital",
            "Inlaks And Budhrani Hospital",
            " Jehangir Hospital",
            " Joglekar Hospital",
            "K E M Hospital",
            "Kamal Nursing Home",
            "Karne Hospital Pvt Ltd",
            "Kataria Hospital",
            "Kohakade Hospital",
            "Krishna General Hospital",
            "Life Line Hospital",
            "Life Point Multispeciality Hospital Pvt Ltd",
            "Lifeline Hospital",
            "Lokmanya Hospital",
            "Lokmanya Hospital",
            "Lunkad Hospital",
            "Mai Mangeshkar Hospital",
            "Manoj Clinic (gore Hospital)",
            "Mantri Hospital",
            "Max Neuro Hospital Private Limited",
            "Mayur Hospital",
            "Medilife Multispeciality Hospital & Icu",
            "Medipoint Hospital",
            "Moraya Hospital",
            "N M Wadia Institute Of Cardiology",
            "Naik Hospital",
            "Nande Hospital",
            "National Institute Of Ophthalmology",
            " Niramaya Hospital",
            " Noble Hospital",
            " Om Hospital",
            " Om Hospital",
            "Omkar Accedent Hospital",
            "Oyster & Pearl Hospital Pvt Ltd ( Tulip Hospital Pvt Ltd)",
            "Oyster & Pearl Hospital Pvt Ltd Run By Phadnis Clinic Pvt Ltd",
            "Paranjpe Eye Clinic & Surgery Center",
            "Parmar Multispeciality Hospital",
            "Patil Hospital",
            "Patil Hospital",
            "Pawana Hospital",
            "Pawar Hospital",
            "Pbmas H V Desai Eye Hospital",
            "Pharande Eye Hospital",
            "Phoenix Hospital",
            "Pioneer Hospital",
            "Pooja Nursing Home",
            "Poona Hospital & Research Centre",
            "Pramodini Urology Foundation",
            "Rakshak Hospital",
            "Ranka Hospital",
            "Rao Nursing Home",
            "Ruby Ailcare Services Pvt Ltd",
            "Ruby Hall Clinic",
            "Ruby Hall Wanowarie",
            "Sahyadri Hospital",
            "Sahyadri Hospital",
            "Sahyadri Hospital",
            "Sahyadri Hospital",
            "Sahyadri Speciality Hospital",
            "Sahyadri Speciality Hospital",
            "Saijyoti Accident Hospital",
            "Sainath Hospital",
            "Saiseva Hospital",
            "Salunke Hospital",
            "Sancheti Institute For Orthopaedics & Rehabilitation",
            "Sangam Hospital",
            "Sanjeevan Hospital",
            "Sanjeevan Maternity & Surgical Hospital",
            "Sanjeevani Nursing Home",
            "Sant Dnyaneshwar Hospital Pvt Ltd",
            "Sayali Nursing Home",
            "Shah Accident Hospital",
            "Shahade Hospital",
            "Shaishav Childrens Hospital And Research Centre Pvt Ltd",
            "Shakun Clinic Children Hospital",
            "Sharada Clinic",
            "Shashwat Hospital Shashwat Health Services Pvt Ltd",
            "Shree Balaji Eye Hospital",
            "Shree Hospital",
            "Shrikhande Clinic",
            "Shubhankar Hospital & Diagnostic Centre",
            "Shwas Multispeciality Hospital",
            "Siddhi Health Care Centre",
            "Siddhi Hospital",
            "Sofia Hospital",
            "Suraj Hospital",
            "Surya Multispeciality Hospital",
            "Surya Sahyadri Hospital",
            "Todkar Hospital",
            "Tongaonkar Hospital",
            "Unicare Hospital",
            " Ushakiran General Hospital",
            " Vaibhavi Hospital",
            " Vatsalya Childrens Hospital",
            " Vinod Memorial Multispeciality Hospital",
            "Sushrut Hospital",
            "Chintamani Hospital",
            "Bhakti Hospital",
            "Jijamata Hospital",
            "Rakshak Hospital",
            "Surya Hospital",
            "Attharva Accident Hospital",
            "Sevadham Hospital",
            "Spandan Hospital",
            "Anand Hospital",
            "Laxmi Icu & Nursing Home",
            "Reliance Hospital Management Srvices Pvt Ltd ( Unit Of Dhirubhai Ambani Hospital )",
            " Dr Dongare Clinic",
            " Jakhotia Nursing Home",
            " Sumitraraj Hospital",
            " Suprama Hospital",
            "Thakur Clinic",
            "Vidyaprabha Hospital",
            "Arunodaya Clinic",
            "Ashtavinayak Hospital",
            "Care Plus Hospital",
            "Dandekar Hospital Panvel",
            "Gandhi Hospital",
            "Life Line Hospital",
            "Mhatre Accident Hospital",
            "Nairs Eye Clinic",
            "Panacea Hospital",
            "Panvel Hospital",
            "Paramount Clinic & Medical Research Centre",
            "Prachin Healthcare Hospital",
            "Purohit Clinic",
            "Sai Child Care Clinic (dr Mohites Amrut Medical Foundation)",
            "Unnati Hospital & Icu",
            "Veer Hospital & Icu",
            "Yash Hospital",
            "Mhatre Hospital",
            "Shree Sai Rugnalaya",
            "Shree Siddhakala Gen Hospital and Research Centre",
            "Soham Hospital",
            "Trimurti Clinic and Maternity Home",
            " Dr.Saroj Tamboli Memorial Hospital",
            " Shree Mhatre Hospital",
            " Shree Narayan Hospital",
            " Dr Bhat Nursing Home",
            "Dr Jadhav Nursing Home & Icu",
            "Dr Wagles Nursing Home",
            "Parkar Hospital &research Institute Pvt Ltd",
            "Parshuram Hospital &research Centre",
            "Shree Ramnath Hospital & Konkan Cardiac Centre",
            "City Medical Centre",
            "K N Gujar Memorial Hospital",
            "Sahyadri Speciality Hospital",
            "Sharda Clinic Erram Multispeciality Hospital",
            "Dr Anil Kulkarni Eye Hospital",
            "Sarvamangal Hospital",
            "Shanti Saroj Netralay",
            "Sushruta Hospital For Orthopaedics & Traumatology",
            "Swasthiyog Pratishthan",
            "Wanless Hospital Miraj Medical Centre",
            "Anuradha Eye Hospital & Polyclinic",
            "Kranti Cardiac Centre",
            "Mehta Hospital",
            "Sarvhit Medical Nursing Home & Icu",
            "Shraddha Surgical & Accident Hospital",
            "Sree Tekke Eye Clinic",
            "Sunita memorial accident & genral hospital & nursing home",
            "V V Ent & Endoscopy Hospital Pvt Ltd",
            "Vasan Eye Care Hospital",
            "Saste Hospital",
            "Shri Siddhivinayak Hospital & Criticare",
            "Institute Of Medical Science & Research Hospital",
            "Chirjeevan Hospital & Research Centre",
            "Joshi Hospital Pvt Ltd",
            "Siddhanath Hospital & Research Centre",
            "Sushrut Hospital",
            "Yash Maternity & Surgical Hospital",
            "Ameya Lesers & Research Pvt Ltd",
            "Criti Care Centre",
            "Datta Kashi Hospital",
            "Dr Jagtap Hospital Pvt Ltd",
            "Dr Patil Ortheopedic Accident Trauma Icu & Eye Hospital",
            "Drishti Eye Hospital Phaco And Laser Centre",
            " Jayanant Hospital For Children",
            " Meenakshi Hospital",
            " Morya Hospital & Research Centre",
            "  Nandadeep Hospital & Research Centre",
            " Onco Life Cancer Centre Pvt Ltd",
            " Pratibha Hospitals Pvt.ltd",
            "Samarth Hospitals Pvt Ltd",
            "Sanjeevan Hospital",
            "Sanjeevan Icu Pvt Ltd",
            "Satara Hospital & Research Centre",
            "Savitri Hospital",
            "Shri Seva Medical Foundation",
            "Wagholikareye Clinic & Phaco Centre",
            "Geetanjali Hospital & Intensive Care Unite",
            "General Hospital",
            "Ghotavadekar Hospital",
            "Modern Clinic",
            "Patange Hospital",
            "Sonia Clinic & Saidutta Hospital Cathlab",
            "Dr Nagvekar Hospital & Nursing Home",
            "Dr S K Parulekar Hospital",
            "Gurukrupa Hospital",
            "Om Kartavya Sadhna Hospital",
            "Yashraj Hospital",
            "Ashwini Hospital",
            "Kadam Multispeciality Hospital",
            "Jadhav Hospitlal",
            "Shah Hospital",
            "Lokmangal Medical Foundation & Resarch Center",
            "Dr Kadam Surgical Hospital",
            "Anand Hospital & Ultrasound centre",
            "Parijat Hospital",
            "Gandhi surgical nursing home",
            "Nandini Hospital",
            "Samarth Hospital",
            "Takle Hospital",
            "Anand Hospital",
            "Ashwini Sahakari Rugnalaya & Research Centre",
            "City Hospital",
            "Dr Chidgupkar Hospital Pvt. Ltd.",
            "Dr Kasliwal Medical Care & Research Foundation",
            "Dr Raghoji Kidney Hospital & Research Centre Pvt Ltd",
            "Dr Valvekar Hospital",
            "Gangamai Hospital",
            "Jain Hospital And Jain Institute Of Digestive Diseases",
            "Kothadia Nursing Home",
            "Raghoji Ent & Maternity Hospital",
            "Shree Samarth Hospital",
            "Shri Markandey Solapur Sah Rugnalaya & Research Centre Niy",
            "Solapur Kidney & Research Centre",
            "Utkarsha Hospital",
            "Vivekanand Nursing Home",
            "Wachche Hospital",
            "Yashodhara Superspeciality Hospital",
            "Aarogyam Multispeciality Hospital",
            "Aarogyam Multispeciality Hospital & Icu",
            "Aashirwad Hospital",
            "Aastha Hospital",
            "Aastha Hospital",
            "Aditya Hospital & Icu",
            "Ahirkar Hospital",
            "Amber Eye Care & Microsurgery Centre",
            "Amrut Hospital & Endoscopy Clinic",
            "Anand General Hospital",
            " Anantlakshmi Hospital & Polyclinic",
            " Anil Eye Hospital",
            "Anish Hospital",
            "Apex Hospital",
            "Apurva Nursing Home",
            "Arth Hospital",
            "Aryan Eye Clinic & Day-care Surgery Centre",
            "Ashirwad Hospital",
            "Ashirwad Maternity & General Hosital",
            "Ashirwad Nursing Home",
            "Asian Institute Of Medical Science",
            "Asmita Nursing Home",
            "Bethany Hospital",
            "Bhagwati Healthcare Private Limited",
            "Bhakti Vedanta Hospital",
            "Cardinal Gracias Memorial Hospital Trust (dir Mailer)",
            "Cauvery Uroderm Centre",
            "Chirayu Medical Foundation",
            "Criti Care Iccu Multispeciality & Trauma Centre",
            "Criticare Superspeciality Hospital",
            "Dhanvantari Diagnostics",
            "Dhanvantari Hospital",
            "Dhanvantri Hospital Pvt Ltd",
            "Dhanwantari Hospital",
            "Dr Amars Karkhanis Super Speciality Hospital",
            "Dr Bhanushali Hospital",
            "Dr Deshpande Ashirwad Hospital",
            "Dr Doshi Children Hospital",
            "Dr Gadgil Eye Hospital",
            "Dr Godboles Heart Care Centre Pvt Ltd",
            "Dr Goyal Children & General Hospital",
            "Dr Harne Hospital",
            "Dr Karavade Eye Clinic",
            "Dr Kulur Hospital",
            "Dr Muddebihalkar Hospital & ICCU",
            "Dr Paradkar Maternity & General Nursing Home",
            "Dr Shah Eye & Laser Centre",
            "Dr Talele Shree Ashirwad Hospital",
            "Dr Uppals Ent Hospital",
            "Dr Wankhade Fracture & Accident Hospital",
            "Dr. Kelkars Eye Hospital",
            "Dr.bedekar Dispensary,maternity And General Hospital &surgical Home",
            "Dsouza Hospital",
            "Fortis Hospital Ltd Kalyan",
            "Gastrocare Hospital",
            "Gayatri Maternity & ENT Hospital",
            "Golden Park Hospital",
            "Gurudeo Maternity & Nursing Home",
            "Gurukrupa Hospital & Polyclinic",
            "Highway Hospital",
            "Hiranandani Hospital",
            "Hi-tech Urology Centre & Health Line Hospital",
            "Holy Cross Hospital",
            "Horizon Hospital",
            "Icon Hospital Pvt Ltd",
            "Indrayani Hospital",
            "Isha Netralaya A Unit Of Dr Shahs Laser Eye Institute",
            "Ishaan Urology Centre",
            "Ishwar Hospital",
            "Jai Hospital",
            "Janam Hospital",
            "Jivdani Hospital Pvt Ltd (alliance Hospital)",
            "Jupiter Lifeline Hospital Ltd",
            "Kalyan Metro Multispeciality Hospital Pvt Ltd",
            "Kamla Eye And Maternity Home",
            "Kaushalya Medical Foundation Trust Hospital",
            "Kaveri Hospital",
            "Kevalya Hospital",
            " Kkasturi Medicare Pvt Ltd",
            "Koparde Hospital",
            "Kumar Maternity & Surgical Nursing Home",
            "Leela Eye Institute",
            "Madhura Nursing Home",
            "Mahalaxmi Hospital",
            "Mahesh Hospital",
            "Mamata Hospital",
            "Manawata Hospital & Smt Nalini Ghag Maternity  Unit",
            "Mangalmurti Hospital & Polyclinic",
            "Mira Bhayander Institute For Reproductive Assistance",
            "Navjeevan Hospital",
            "Navjeevan Nursing Home",
            "Neel Orthopedic Superspeciality Hospital",
            "Neptune Superspeciality Hospital",
            "Nest Accident & Fracture Hospital",
            "Nulife Hospital",
            " Om Hospital",
            "Om Hospital & Polyclinic & Icu",
            "Orange Hospital",
            "Orbit Superspeciality Hospital",
            "Orthocare Hospital",
            "Orthonova Hospital",
            "Padmini Hospital",
            "Param Hospital & I. C. U.",
            "Phadke Hospital",
            "Phoenix Hospital & Critical Care Centre",
            "Platinum Hospital Pvt Ltd",
            "Pooja Nursing Home",
            "Prakash Nursing Home",
            "Prakruti Hospital",
            "Pranjali Maternity Surgical & General Hospital",
            "R G Stone In Collaboration With Bhakti Vedanta Hospital",
            "R L Ent Hospital",
            "R R Hospital ( Unit Of Kagzi Hospital & Medical Research Centre )",
            "Ramanand Hospital/ Icu",
            "Renuka Hospital and ICCU",
            "Revival Bone And Joint Hospital",
            "Risk Care Hospital & I C C U",
            "Sahayog Hospital & Research Centre",
            "Sai Jyothi Hospital",
            "Sai Leela Hospital",
            "Sai Seva Hospital",
            "Sai Shraddha Hospital",
            "Saibaba Hospital & Polyclinic",
            "Saikrupa Hospital",
            "Salasar Nursing Home",
            "Samarth Nursing Home",
            "Samartha Hospital",
            "Samata Hospital And Polyclinic",
            "Sampada Hospital",
            "Sanjeevani Children Hospital",
            "Sanjivani Hospital",
            "Sapphire Hospital",
            "Saxena Children & General Hospital",
            "Senses Eye & Ent Hospital",
            "Shahlife Line Hospital",
            "Shalom Medicare Pvt Ltd",
            " Shivam Hospital",
            " Shobha Hospital",
            "Shraddha General Hospital",
            "Shree Hospital",
            "Shree Sai Hospital",
            "Shree Siddhivinayak Orthopaedic Hospital",
            "Shreedevi Hospital",
            "Shreyas Hospital",
            "Shrinivas Hospital",
            "Shriram Nursing Home",
            "Shushrusha Hospital",
            "Surekha Criticare Hospital",
            "Sushrut Hospital",
            "Suyash Hospital",
            " Suyash Nursing Home",
            " Swastik Hospital & Urology Centre",
            "Tanmay Health Care",
            " Tanwar Hospital",
            "Thane Eye Care Hospital",
            "Thane Health Care Hospital",
            "Thunga Hospital",
            "Thunga Hospital Pvt Ltd",
            "Titan Hospital",
            "Trupti Maternity, Surgical & General Hospital",
            " Vasan Eye Care Hospital",
            "Vasan Eye Care Hospital",
            "Ved Hospital Superspeciality & Medical Research Pvt Ltd",
            "Vedant Hospital",
            " Vedant Multispeciality Hospital & Research Centre",
            "Venkatesh Hospital",
            "Wockhardt Hospital Ltd",
            "Jain Hospital",
            "Krishna Hospital",
            "Sainath Nursing Home",
            "Sunetra Eye Hospital",
            "Kariya Hospital",
            "Sanjeevan Multispeciality Hospital & Research Institute",
            "Shanti Orthopaedic Hospital",
            "Tawde Hospital"
    };

    String[] groups = {"A+","A-","B+","B-","AB+","AB-","O+","O-"};


    ArrayAdapter<String> distAdapter,hospitalAdapter,groupAdapter;
    private static final int galleryPick = 1;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_settings);

        circleImageView = (CircleImageView)findViewById(R.id.profile_image);
        loadingBar = new ProgressDialog(this);
        fullnameEditText = (EditText)findViewById(R.id.fullnameEditText);
        ageEditText = (EditText)findViewById(R.id.ageEditText);
        bloodGroupEditText = (AutoCompleteTextView) findViewById(R.id.BloodGroupEditText);
        thanaEdit = (EditText)findViewById(R.id.thanaEditText);
        districtEdit = (AutoCompleteTextView) findViewById(R.id.districtEditText);
        contactEdit = (EditText)findViewById(R.id.ContactEditText);
        hospitalEdit = (AutoCompleteTextView) findViewById(R.id.hospitalEditText);
        donationdate = (EditText)findViewById(R.id.lastdonationEditText);
        Button submitButton = (Button) findViewById(R.id.submitButtonId);
        calenderIcon = (ImageView)findViewById(R.id.calenderIcon);


        distAdapter = new ArrayAdapter<>(this,android.R.layout.simple_dropdown_item_1line,districts);
        districtEdit.setThreshold(1);
        districtEdit.setAdapter(distAdapter);

        groupAdapter = new ArrayAdapter<>(this,android.R.layout.simple_dropdown_item_1line,groups);
        bloodGroupEditText.setThreshold(1);
        bloodGroupEditText.setAdapter(groupAdapter);

        hospitalAdapter = new ArrayAdapter<>(this,android.R.layout.simple_dropdown_item_1line,hospitals);
        hospitalEdit.setThreshold(1);
        hospitalEdit.setAdapter(hospitalAdapter);

        Calendar calendar = Calendar.getInstance();
        final int year = calendar.get(Calendar.YEAR);
        final int month = calendar.get(Calendar.MONTH);
        final int day = calendar.get(Calendar.DAY_OF_MONTH);

        mAuth = FirebaseAuth.getInstance();
        currentUser = mAuth.getCurrentUser();
        currentUserID = mAuth.getCurrentUser().getUid().toString();
        RootRef = FirebaseDatabase.getInstance().getReference();
        storageReference = FirebaseStorage.getInstance().getReference().child("profile_images");

        circleImageView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                chooseImage();
            }
        });

       calenderIcon.setOnClickListener(new View.OnClickListener() {
           @Override
           public void onClick(View v) {

               DatePickerDialog datePickerDialog;
               datePickerDialog = new DatePickerDialog(SettingsActivity.this,  new DatePickerDialog.OnDateSetListener() {
                   @Override
                   public void onDateSet(DatePicker view, int year, int month, int dayOfMonth) {
                       month = month + 1;
                       String date = dayOfMonth + "/" + month + "/" + year;
                       donationdate.setText(date);
                   }
               },year,month,day);



               datePickerDialog.show();



           }
       });



        submitButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                saveData();

            }
        });
    }



    private void chooseImage() {

            Intent galleryIntent = new Intent();
            galleryIntent.setAction(Intent.ACTION_GET_CONTENT);
            galleryIntent.setType("image/*");
            startActivityForResult(galleryIntent,galleryPick);
    }
    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        try{
            super.onActivityResult(requestCode, resultCode, data);

            if (requestCode == galleryPick && resultCode == RESULT_OK && data != null) {
                imageUri = data.getData();

                imageStore = MediaStore.Images.Media.getBitmap(getContentResolver(),imageUri);
                circleImageView.setImageBitmap(imageStore);

            }
        }
        catch (Exception e){
            Toast.makeText(this, e.getMessage().toString(), Toast.LENGTH_SHORT).show();
        }
    }

    public String getFileExtension(Uri imageUri){
        ContentResolver contentResolver = getContentResolver();
        MimeTypeMap mimeTypeMap = MimeTypeMap.getSingleton();
        return mimeTypeMap.getExtensionFromMimeType(contentResolver.getType(imageUri));
    }

    private void saveData() {

        final String name = fullnameEditText.getText().toString();
        final String age = ageEditText.getText().toString();
        final String bloodGroup = bloodGroupEditText.getText().toString();
        final String thana = thanaEdit.getText().toString();
        final String district = districtEdit.getText().toString();
        final String contact = contactEdit.getText().toString();
        final String hospital = hospitalEdit.getText().toString();
        final String lastDate = donationdate.getText().toString();

        if(TextUtils.isEmpty(name)){
            fullnameEditText.setError("please give your name");
            fullnameEditText.requestFocus();
            return;
        }
        if(TextUtils.isEmpty(age)){
            ageEditText.setError("please give your age");
            fullnameEditText.requestFocus();
            return;
        }
        if(TextUtils.isEmpty(bloodGroup)){
            bloodGroupEditText.setError("please give your Blood Group");
            bloodGroupEditText.requestFocus();
            return;
        }

        if(TextUtils.isEmpty(thana)){
            thanaEdit.setError("give your thana name");
            thanaEdit.requestFocus();
            return;
        }
        if(TextUtils.isEmpty(district)){
            districtEdit.requestFocus();
            districtEdit.setError("give your district name");
            return;
        }
        if(TextUtils.isEmpty(contact)){
            contactEdit.setError("contact number please");
            contactEdit.requestFocus();
            return;
        }
        if(TextUtils.isEmpty(lastDate)){
            donationdate.requestFocus();
            donationdate.setError("please enter the last donation date");
            return;
        }
        if(TextUtils.isEmpty(hospital)){
            hospitalEdit.setError("nearest hospital name");
            hospitalEdit.requestFocus();
            return;
        }

        else{
            loadingBar.setTitle("Register");
            loadingBar.setMessage("Your information is uploading");

            loadingBar.setCanceledOnTouchOutside(true);
            loadingBar.show();


            StorageReference filePath = storageReference.child(currentUserID+"." +getFileExtension(imageUri));
            filePath.putFile(imageUri)
                    .addOnSuccessListener(new OnSuccessListener<UploadTask.TaskSnapshot>() {
                        @Override
                        public void onSuccess(UploadTask.TaskSnapshot taskSnapshot) {
                            Task<Uri> uriTask = taskSnapshot.getStorage().getDownloadUrl();
                            while(!uriTask.isSuccessful());
                            Uri downloadUrl = uriTask.getResult();

                            Upload upload = new Upload(name,age,bloodGroup,thana,district,contact,hospital,downloadUrl.toString(),lastDate);
                            HashMap hash = new HashMap();
                            hash.put("district",district);
                            hash.put("hospital",hospital);

                            RootRef.child(bloodGroup).child(currentUserID).setValue(hash);
                            RootRef.child("Users").child(currentUserID).setValue(upload);
                            loadingBar.dismiss();
                            Intent mainIntent = new Intent(getApplicationContext(),FirstActivity.class);
                            startActivity(mainIntent);
                            Toast.makeText(SettingsActivity.this, "Successfully stored in firestore", Toast.LENGTH_SHORT).show();

                        }
                    })
                    .addOnFailureListener(new OnFailureListener() {
                        @Override
                        public void onFailure(@NonNull Exception exception) {
                            Toast.makeText(SettingsActivity.this, "Error :"+exception, Toast.LENGTH_SHORT).show();
                        }
                    });



        }

    }



}
